###MySQL Settings
Database:
   #Insert mysql or mongodb here
   Type: "mysql"
   Host: "localhost"
   Port: 3306
   Username: "root"
   Password: ""
   Databasename: "devtests"
   Tableprefix: "bs_"
###For sending debug messages
Debug: false
LogPrefix: "[BukkitStats]"
ChatPrefix: "&a[BukkitStats]"